In [1]:
import numpy as np
from numpy import linalg as la

In [2]:
def f(N):
    while N>3:
        if N % 3 == 0:
            N = N/3
        else:
            N = N-1
    return N

In [3]:
f(24),f(31)

(2.0, 3.0)

In [4]:
5*3-6

9

In [5]:
a = 5
b = 6
a*b

30

In [6]:
def sjx(a, b):
    return a*b-(a+b)

In [7]:
sjx(5, sjx(14, 6))

251

In [8]:
def zfx(a, b):
    sum1 = 0
    for i in range(b):
        sum1 = sum1 + a
        a= a+1
    return sum1


In [9]:
zfx(2017, 37)

75295

In [10]:
zfx(12,5)

70

In [11]:
zfx(5,6)

45

In [12]:
5+6+7+8+9+10

45

In [13]:
zfx(1,10), zfx(1,100), zfx(1,1000), zfx(1,10000)

(55, 5050, 500500, 50005000)

In [14]:
def f(n,m):
    if(n==1):
        return 1
    if(m==1):
        return n
    return f(n-1,m)+f(n,m-1)

In [15]:
f(3,3)

10

In [16]:
def makeSigma(s, n=0):
    if(n==0):
        n = len(s)
    sigma = np.zeros((n,n))
    for i in range(n):
        sigma[i,i] = s[i]
    return sigma

In [23]:
eigVals,eigVects = np.linalg.eig(np.mat([[-1,2],[2,-1]]))
eigVals,eigVects.A

(array([ 1., -3.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [29]:
np.dot(np.dot(eigVects ,makeSigma(eigVals)), la.inv(eigVects) )

matrix([[-1.,  2.],
        [ 2., -1.]])

In [25]:
U, Sigma, Vt = np.linalg.svd(np.mat([[-1,2],[2,-1]]))
U, Sigma, Vt 

(matrix([[-0.70710678,  0.70710678],
         [ 0.70710678,  0.70710678]]),
 array([3., 1.]),
 matrix([[ 0.70710678, -0.70710678],
         [ 0.70710678,  0.70710678]]))

In [26]:
np.dot(np.dot(U,makeSigma(Sigma)), Vt)

matrix([[-1.,  2.],
        [ 2., -1.]])

In [30]:
dat = np.mat([[1,2],[2,3],[3,4]])

In [31]:
U, Sigma, Vt = np.linalg.svd(dat)
U, Sigma, Vt 

(matrix([[-0.33809817,  0.84795222,  0.40824829],
         [-0.55064932,  0.17354729, -0.81649658],
         [-0.76320047, -0.50085764,  0.40824829]]),
 array([6.54675564, 0.37415323]),
 matrix([[-0.56959484, -0.82192562],
         [-0.82192562,  0.56959484]]))

In [34]:
eigVals,eigVects = np.linalg.eig(np.dot(dat.T , dat))
eigVals,eigVects.A

(array([ 0.13999064, 42.86000936]), array([[-0.82192562, -0.56959484],
        [ 0.56959484, -0.82192562]]))